---
- name: Cloud Dev Enviroment
  hosts: cloud_servers
  gather_facts: no
  pre_tasks:
    - name: Install aptitude
      raw: test ! -e /usr/bin/aptitude && sudo apt-get install -qq aptitude || true

    - name: Install python 2.7
      raw: test ! -e /usr/bin/python && (sudo apt-get update -qq && sudo apt-get install -qq python2.7) || true

    - name: Install letsencrypt 
      raw: test ! -e /usr/bin/letsencrypt && (sudo apt-get update -qq && sudo apt-get install -qq letsencrypt) || true
                                                  i
    - name: Gather Facts
      setup:

  roles:
    - common
    - dev
    - ufw
